language: python
python:
  - 2.6
  - 2.7
env:
  - DJANGO=Django==1.3.0
  - DJANGO=Django==1.4.0
  - DJANGO=Django==1.5.0
  - DJANGO=Django==1.6.0
install:
  - pip install -q $DJANGO
script:
  - nosetests tests.py
